export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL'


export const CHAT_FETCH_REQUEST = 'CHAT_FETCH_REQUEST'
export const CHAT_FETCH_SUCCESS = 'CHAT_FETCH_SUCCESS'
export const CHAT_FETCH_FAIL = 'CHAT_FETCH_FAIL'
export const CHAT_CLEAR = 'CHAT_CLEAR'



export const TOGGLE_FETCH_POSTS = 'TOGGLE_FETCH_POSTS'



export const CONVERSATION_LIST_REQUEST = 'CONVERSATION_LIST_REQUEST'
export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS'
export const CONVERSATION_LIST_FAIL = 'CONVERSATION_LIST_FAIL'



export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST'
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS'
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL'
export const CHAT_CREATE_RESET = 'CHAT_CREATE_RESET'


export const MESSSAGE_DELETE_REQUEST = 'MESSSAGE_DELETE_REQUEST'
export const MESSSAGE_DELETE_SUCCESS = 'MESSSAGE_DELETE_SUCCESS'
export const MESSSAGE_DELETE_FAIL = 'MESSSAGE_DELETE_FAIL'
