export const POST_LIST_REQUEST = 'POST_LIST_REQUEST'
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS'
export const POST_LIST_FAIL = 'POST_LIST_FAIL'

export const GALLERY_LIST_REQUEST = 'GALLERY_LIST_REQUEST'
export const GALLERY_LIST_SUCCESS = 'GALLERY_LIST_SUCCESS'
export const GALLERY_LIST_FAIL = 'GALLERY_LIST_FAIL'

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAIL = 'COMMENT_LIST_FAIL'



export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL'




export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL'
export const POST_CREATE_RESET = 'POST_CREATE_RESET'

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST'
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL'
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET'



export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST'
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS'
export const POST_CREATE_COMMENT_FAIL = 'POST_CREATE_COMMENT_FAIL'
export const POST_CREATE_COMMENT_RESET = 'POST_CREATE_COMMENT_RESET'





export const BOOKMARK_CREATE_REQUEST = 'BOOKMARK_CREATE_REQUEST'
export const BOOKMARK_CREATE_SUCCESS = 'BOOKMARK_CREATE_SUCCESS'
export const BOOKMARK_CREATE_FAIL = 'BOOKMARK_CREATE_FAIL' 

export const LIKE_CREATE_REQUEST = 'LIKE_CREATE_REQUEST'
export const LIKE_CREATE_SUCCESS = 'LIKE_CREATE_SUCCESS'
export const LIKE_CREATE_FAIL = 'LIKE_CREATE_FAIL' 




export const BOOKMARK_LIST_MY_REQUEST = 'BOOKMARK_LIST_MY_REQUEST'
export const BOOKMARK_LIST_MY_SUCCESS = 'BOOKMARK_LIST_MY_SUCCESS'
export const BOOKMARK_LIST_MY_FAIL = 'BOOKMARK_LIST_MY_FAIL' 
export const BOOKMARK_LIST_MY_RESET = 'BOOKMARK_LIST_MY_RESET' 


